[book]
authors = ["Olaf Kolkman (editor)"]
language = "en"
multilingual = false
src = "src"
title = "IETF Ornithology: Potential Public Policy Aspects in IETF 124"




[output.html]

git-repository-url = "https://github.com/internetsociety/IETF-Ornithology/"
pdf-download-url = "https://internetsociety.github.io/IETF-Ornithology/IETF-Ornithology.pdf"
theme = "ornitheme"
favicon_png ="https://www.internetsociety.org/wp-content/themes/isoc/dist/images/favicon/favicon-96x96.png"

# [preprocessor.last-changed]
# command = "mdbook-last-changed"
# renderer = ["html"]

[output.html.print]
enable = false    # include support for printable output


[output.pandoc.profile.latex]
output-file = "output.latex"

[output.pandoc.profile.pdf]

pdf-engine = "lualatex"
output-file = "IETF-Ornithology.pdf"
to = "latex"
table-of-contents = true
standalone = true

template = "ISOCTemplate.tex"


[output.pandoc.profile.pdf.variables]
logo = "ISOCShield.png"
subtitle = "A Curated Overview"
graphics = true
standalone = true # produce output with an appropriate header and footer
titlegraphic= "ISOCLogo.png"
# mainfont= "Hind-Light.ttf"
mainfont="open-sans"
documentclass= "article"
toc-depth=4

classoption= [ "a4paper" ]

pagestyle= "headings"

colorlinks=true
